output_file: docker-compose.yaml

# Configuraci칩n de monitores
monitors:
  count: 2
  base_port: 50000
  cluster_base_port: 50010
  # Configuraci칩n de heartbeat (m치s r치pido para testing)
  heartbeat_interval: 3000      # 3 segundos
  heartbeat_timeout: 10000      # 10 segundos
  election_timeout: 8000        # 8 segundos

clients:
  - id: 1
    files_path: ./files/mini

workers:
  twentieth_century: 1
  main_movie: 1
  esp_production: 1
  no_colab_productions: 1
  sentiment: 1
  arg_production: 1
  credits: 1
  ratings: 1

test: false