output_file: docker-compose.yaml

monitors:
  count: 3
  base_port: 50000
  cluster_base_port: 50010
  heartbeat_interval: 100      # 100 milisegundos
  heartbeat_timeout: 3000      # 3 segundos
  election_timeout: 1000       # 1 segundo

clients:
  - id: 1
    files_path: ./files/long
  - id: 2
    files_path: ./files/long

workers:
  twentieth_century:
    count: 2
    log_level: INFO
    kill: true
  main_movie:
    count: 2
    log_level: INFO
    kill: true
  esp_production:
    count: 2
    log_level: INFO
    kill: true
  no_colab_productions:
    count: 1
    log_level: INFO
    kill: true
  sentiment:
    count: 3
    log_level: INFO
    kill: true
  arg_production:
    count: 1
    log_level: INFO
    kill: true
  credits:
    count: 2
    log_level: INFO
    kill: true
  ratings:
    count: 2
    log_level: INFO
    kill: true
client_decodifier:
  count: 1
  log_level: INFO
  kill: true

aggregators:
  twentieth_century_arg_esp:
    generate: true
    log_level: INFO
    kill: true
  twentieth_century_arg:
    generate: true
    log_level: INFO
    kill: true
  top_5_countries:
    generate: true
    log_level: INFO
    kill: true
  top_10_credits:
    generate: true
    log_level: INFO
    kill: true
  best_and_worst_ratings:
    generate: true
    log_level: INFO
    kill: true
  sentiment:
    generate: true
    log_level: INFO
    kill: false

test:
  random: true
  interval: 5