output_file: docker-compose.yaml

# Configuración de monitores
monitors:
  count: 1
  base_port: 50000
  cluster_base_port: 50010
  # Configuración de heartbeat (muy rápido para testing)
  heartbeat_interval: 2000      # 2 segundos
  heartbeat_timeout: 8000       # 8 segundos
  election_timeout: 5000        # 5 segundos

clients:
  - id: 1
    files_path: ./files/short

workers:
  twentieth_century:
    count: 1
    log_level: INFO
    kill: true
  main_movie:
    count: 1
    log_level: DEBUG
    kill: true
  esp_production:
    count: 1
    log_level: INFO
    kill: true
  no_colab_productions:
    count: 1
    log_level: INFO
    kill: true
  sentiment:
    count: 1
    log_level: INFO
    kill: false
  arg_production:
    count: 1
    log_level: INFO
    kill: true
  credits:
    count: 1
    log_level: INFO
    kill: false
  ratings:
    count: 1
    log_level: INFO
    kill: false

aggregators:
  twentieth_century_arg_esp:
    generate: true
    log_level: INFO
    kill: true
  twentieth_century_arg:
    generate: true
    log_level: INFO
    kill: true
  top_5_countries:
    generate: true
    log_level: INFO
    kill: true
  top_10_credits:
    generate: true
    log_level: INFO
    kill: false
  best_and_worst_ratings:
    generate: true
    log_level: INFO
    kill: false
  sentiment:
    generate: true
    log_level: INFO
    kill: false

test:
  random: true
  interval: 11