output_file: docker-compose.yaml

clients:
  - id: 1
    files_path: ./files/short/

workers:
  twentieth_century: 1
  main_movie: 1
  esp_production: 1
  no_colab_productions: 1
  sentiment: 1
  arg_production: 1
  credits: 1
  ratings: 1

test: false