output_file: docker-compose.yaml

clients:
  - id: 1
    files_path: ./files/short

workers:
  twentieth_century:
    count: 1
    log_level: INFO
    kill: false
  main_movie:
    count: 1
    log_level: DEBUG
    kill: false
  esp_production:
    count: 1
    log_level: INFO
    kill: false
  no_colab_productions:
    count: 1
    log_level: INFO
    kill: false
  sentiment:
    count: 0
    log_level: INFO
    kill: false
  arg_production:
    count: 1
    log_level: INFO
    kill: false
  credits:
    count: 2
    log_level: INFO
    kill: false
  ratings:
    count: 3
    log_level: INFO
    kill: false

aggregators:
  twentieth_century_arg_esp:
    generate: true
    log_level: INFO
    kill: false
  twentieth_century_arg:
    generate: true
    log_level: INFO
    kill: false
  top_5_countries:
    generate: true
    log_level: INFO
    kill: false
  top_10_credits:
    generate: true
    log_level: INFO
    kill: true
  best_and_worst_ratings:
    generate: true
    log_level: INFO
    kill: false
  sentiment:
    generate: false
    log_level: INFO
    kill: false

test:
  random: false
  interval: 1