output_file: docker-compose.yaml

monitors:
  count: 2
  base_port: 50000
  cluster_base_port: 50010

  heartbeat_interval: 100      # 100 milisegundos
  heartbeat_timeout: 3000      # 3 segundos
  election_timeout: 1000       # 1 segundo

clients:
  - id: 1
    files_path: ./files/mini

workers:
  twentieth_century: 1
  main_movie: 1
  esp_production: 1
  no_colab_productions: 1
  sentiment: 1
  arg_production: 1
  credits: 1
  ratings: 1

test: false