services:
  arg_production_filter:
    build:
      context: .
      dockerfile: filters/arg_production/arg_production_filter.dockerfile
    depends_on:
      monitor_1:
        condition: service_started
      monitor_2:
        condition: service_started
      monitor_3:
        condition: service_started
      monitor_4:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      worker:
        condition: service_started
    environment:
    - PYTHONUNBUFFERED=1
    - LOG_LEVEL=INFO
    - MONITOR_HOSTS=monitor_1,monitor_2,monitor_3,monitor_4
    - MONITOR_PORTS=50001,50002,50003,50004
    - HEARTBEAT_INTERVAL=5000
    - SERVICE_NAME=arg_production_filter
    image: arg_production_filter:latest
    links:
    - rabbitmq
  best_and_worst_ratings_aggregator:
    container_name: best_and_worst_ratings_aggregator
    build:
      context: .
      dockerfile: aggregator/best_and_worst_ratings_aggregator/aggregator.dockerfile
    depends_on:
      monitor_1:
        condition: service_started
      monitor_2:
        condition: service_started
      monitor_3:
        condition: service_started
      monitor_4:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      worker:
        condition: service_started
    environment:
    - PYTHONUNBUFFERED=1
    - LOG_LEVEL=INFO
    - MONITOR_HOSTS=monitor_1,monitor_2,monitor_3,monitor_4
    - MONITOR_PORTS=50001,50002,50003,50004
    - HEARTBEAT_INTERVAL=5000
    - SERVICE_NAME=best_and_worst_ratings_aggregator
    links:
    - rabbitmq
    ports:
    - 60001:60001
  client_1:
    build:
      context: .
      dockerfile: client/client.dockerfile
    container_name: client_1
    depends_on:
      client_decodifier:
        condition: service_healthy
      monitor_1:
        condition: service_started
      monitor_2:
        condition: service_started
      monitor_3:
        condition: service_started
      monitor_4:
        condition: service_started
    environment:
    - PYTHONUNBUFFERED=1
    - DECODIFIER_HOST=client_decodifier
    - DECODIFIER_PORT=50000
    - CLIENT_ID=1
    - MONITOR_HOSTS=monitor_1,monitor_2,monitor_3,monitor_4
    - MONITOR_PORTS=50001,50002,50003,50004
    - HEARTBEAT_INTERVAL=5000
    - SERVICE_NAME=client_1
    volumes:
    - ./files/short/movies_metadata.csv:/root/files/movies_metadata.csv
    - ./files/short/credits.csv:/root/files/credits.csv
    - ./files/short/ratings.csv:/root/files/ratings.csv
    - ./results/short/results.json:/root/results/results.json
  client_2:
    build:
      context: .
      dockerfile: client/client.dockerfile
    container_name: client_2
    depends_on:
      client_decodifier:
        condition: service_healthy
      monitor_1:
        condition: service_started
      monitor_2:
        condition: service_started
      monitor_3:
        condition: service_started
    environment:
    - PYTHONUNBUFFERED=1
    - DECODIFIER_HOST=client_decodifier
    - DECODIFIER_PORT=50000
    - CLIENT_ID=2
    - MONITOR_HOSTS=monitor_1,monitor_2,monitor_3
    - MONITOR_PORTS=50001,50002,50003
    - HEARTBEAT_INTERVAL=5000
    - SERVICE_NAME=client_2
    volumes:
    - ./files/long/movies_metadata.csv:/root/files/movies_metadata.csv
    - ./files/long/credits.csv:/root/files/credits.csv
    - ./files/long/ratings.csv:/root/files/ratings.csv
    - ./results/long/results.json:/root/results/results.json
  client_decodifier:
    build:
      context: .
      dockerfile: client_decodifier/client_decodifier.dockerfile
    depends_on:
      monitor_1:
        condition: service_started
      monitor_2:
        condition: service_started
      monitor_3:
        condition: service_started
      monitor_4:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      worker:
        condition: service_started
    environment:
    - MONITOR_HOSTS=monitor_1,monitor_2,monitor_3,monitor_4
    - MONITOR_PORTS=50001,50002,50003,50004
    - HEARTBEAT_INTERVAL=5000
    - SERVICE_NAME=client_decodifier
    healthcheck:
      interval: 5s
      retries: 10
      test: netstat -ltn | grep -c 5000
      timeout: 2s
    ports:
    - 50000:50000
    - 60000:60000
  credits_joiner:
    build:
      context: .
      dockerfile: joiner/credits/credits_joiner.dockerfile
    depends_on:
      monitor_1:
        condition: service_started
      monitor_2:
        condition: service_started
      monitor_3:
        condition: service_started
      monitor_4:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      worker:
        condition: service_started
    environment:
    - PYTHONUNBUFFERED=1
    - LOG_LEVEL=INFO
    - MONITOR_HOSTS=monitor_1,monitor_2,monitor_3,monitor_4
    - MONITOR_PORTS=50001,50002,50003,50004
    - HEARTBEAT_INTERVAL=5000
    - SERVICE_NAME=credits_joiner
    - AGGREGATOR_HOST=aggregator_top_10
    - AGGREGATOR_PORT=60002
    image: credits_joiner:latest
    links:
    - rabbitmq
  esp_production_filter:
    build:
      context: .
      dockerfile: filters/esp_production/esp_production_filter.dockerfile
    depends_on:
      monitor_1:
        condition: service_started
      monitor_2:
        condition: service_started
      monitor_3:
        condition: service_started
      monitor_4:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      worker:
        condition: service_started
    environment:
    - PYTHONUNBUFFERED=1
    - LOG_LEVEL=INFO
    - MONITOR_HOSTS=monitor_1,monitor_2,monitor_3,monitor_4
    - MONITOR_PORTS=50001,50002,50003,50004
    - HEARTBEAT_INTERVAL=5000
    - SERVICE_NAME=esp_production_filter
    image: esp_production_filter:latest
    links:
    - rabbitmq
  esp_production_filter_1:
    depends_on:
      monitor_1:
        condition: service_started
      monitor_2:
        condition: service_started
      monitor_3:
        condition: service_started
      monitor_4:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      worker:
        condition: service_started
    environment:
    - PYTHONUNBUFFERED=1
    - MONITOR_HOSTS=monitor_1,monitor_2,monitor_3,monitor_4
    - MONITOR_PORTS=50001,50002,50003,50004
    - HEARTBEAT_INTERVAL=5000
    - SERVICE_NAME=esp_production_filter_1
    image: esp_production_filter:latest
    links:
    - rabbitmq
  main_movie_filter:
    build:
      context: .
      dockerfile: filters/main_movie_filter/main_movie_filter.dockerfile
    depends_on:
      monitor_1:
        condition: service_started
      monitor_2:
        condition: service_started
      monitor_3:
        condition: service_started
      monitor_4:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      worker:
        condition: service_started
    environment:
    - PYTHONUNBUFFERED=1
    - LOG_LEVEL=INFO
    - MONITOR_HOSTS=monitor_1,monitor_2,monitor_3,monitor_4
    - MONITOR_PORTS=50001,50002,50003,50004
    - HEARTBEAT_INTERVAL=5000
    - SERVICE_NAME=main_movie_filter
    image: main_movie_filter:latest
    links:
    - rabbitmq
  main_movie_filter_1:
    depends_on:
      monitor_1:
        condition: service_started
      monitor_2:
        condition: service_started
      monitor_3:
        condition: service_started
      monitor_4:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      worker:
        condition: service_started
    environment:
    - PYTHONUNBUFFERED=1
    - MONITOR_HOSTS=monitor_1,monitor_2,monitor_3,monitor_4
    - MONITOR_PORTS=50001,50002,50003,50004
    - HEARTBEAT_INTERVAL=5000
    - SERVICE_NAME=main_movie_filter_1
    image: main_movie_filter:latest
    links:
    - rabbitmq
  monitor_1:
    build:
      context: .
      dockerfile: monitor/monitor_cluster.dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - MONITOR_SERVICE_PORT=50001
    - MONITOR_CLUSTER_PORT=50011
    - HEARTBEAT_INTERVAL=5000
    - HEARTBEAT_TIMEOUT=15000
    - MONITOR_NODE_ID=1
    - MONITOR_CLUSTER_NODES=monitor_1,monitor_2,monitor_3,monitor_4
    - EXPECTED_SERVICES=worker,client_decodifier,client_1,twentieth_century_filter,twentieth_century_filter_1,arg_production_filter,credits_joiner,ratings_joiner,main_movie_filter,main_movie_filter_1,esp_production_filter,esp_production_filter_1,no_colab_productions_filter,sentiment_filter,twentieth_century_arg_esp_aggregator,twentieth_century_arg_aggregator,top_5_countries_aggregator,top_10_credits_aggregator,best_and_worst_ratings_aggregator,sentiment_aggregator
    ports:
    - 50001:50001
    - 50011:50011
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  monitor_2:
    build:
      context: .
      dockerfile: monitor/monitor_cluster.dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - MONITOR_SERVICE_PORT=50002
    - MONITOR_CLUSTER_PORT=50012
    - HEARTBEAT_INTERVAL=5000
    - HEARTBEAT_TIMEOUT=15000
    - MONITOR_NODE_ID=2
    - MONITOR_CLUSTER_NODES=monitor_1,monitor_2,monitor_3,monitor_4
    - EXPECTED_SERVICES=worker,client_decodifier,client_1,twentieth_century_filter,twentieth_century_filter_1,arg_production_filter,credits_joiner,ratings_joiner,main_movie_filter,main_movie_filter_1,esp_production_filter,esp_production_filter_1,no_colab_productions_filter,sentiment_filter,twentieth_century_arg_esp_aggregator,twentieth_century_arg_aggregator,top_5_countries_aggregator,top_10_credits_aggregator,best_and_worst_ratings_aggregator,sentiment_aggregator
    ports:
    - 50002:50002
    - 50012:50012
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  monitor_3:
    build:
      context: .
      dockerfile: monitor/monitor_cluster.dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - MONITOR_SERVICE_PORT=50003
    - MONITOR_CLUSTER_PORT=50013
    - HEARTBEAT_INTERVAL=5000
    - HEARTBEAT_TIMEOUT=15000
    - MONITOR_NODE_ID=3
    - MONITOR_CLUSTER_NODES=monitor_1,monitor_2,monitor_3,monitor_4
    - EXPECTED_SERVICES=worker,client_decodifier,client_1,twentieth_century_filter,twentieth_century_filter_1,arg_production_filter,credits_joiner,ratings_joiner,main_movie_filter,main_movie_filter_1,esp_production_filter,esp_production_filter_1,no_colab_productions_filter,sentiment_filter,twentieth_century_arg_esp_aggregator,twentieth_century_arg_aggregator,top_5_countries_aggregator,top_10_credits_aggregator,best_and_worst_ratings_aggregator,sentiment_aggregator
    ports:
    - 50003:50003
    - 50013:50013
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  monitor_4:
    build:
      context: .
      dockerfile: monitor/monitor_cluster.dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - MONITOR_SERVICE_PORT=50004
    - MONITOR_CLUSTER_PORT=50014
    - HEARTBEAT_INTERVAL=5000
    - HEARTBEAT_TIMEOUT=15000
    - MONITOR_NODE_ID=4
    - MONITOR_CLUSTER_NODES=monitor_1,monitor_2,monitor_3,monitor_4
    - EXPECTED_SERVICES=worker,client_decodifier,client_1,twentieth_century_filter,twentieth_century_filter_1,arg_production_filter,credits_joiner,ratings_joiner,main_movie_filter,main_movie_filter_1,esp_production_filter,esp_production_filter_1,no_colab_productions_filter,sentiment_filter,twentieth_century_arg_esp_aggregator,twentieth_century_arg_aggregator,top_5_countries_aggregator,top_10_credits_aggregator,best_and_worst_ratings_aggregator,sentiment_aggregator
    ports:
    - 50004:50004
    - 50014:50014
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  no_colab_productions_filter:
    build:
      context: .
      dockerfile: filters/no_colab_productions/no_colab_productions_filter.dockerfile
    depends_on:
      monitor_1:
        condition: service_started
      monitor_2:
        condition: service_started
      monitor_3:
        condition: service_started
      monitor_4:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      worker:
        condition: service_started
    environment:
    - PYTHONUNBUFFERED=1
    - LOG_LEVEL=INFO
    - MONITOR_HOSTS=monitor_1,monitor_2,monitor_3,monitor_4
    - MONITOR_PORTS=50001,50002,50003,50004
    - HEARTBEAT_INTERVAL=5000
    - SERVICE_NAME=no_colab_productions_filter
    image: no_colab_productions_filter:latest
    links:
    - rabbitmq
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    healthcheck:
      interval: 10s
      retries: 10
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 5s
    ports:
    - 15672:15672
    volumes:
    - ./rabbitmq/config.ini:/config.ini
  ratings_joiner:
    build:
      context: .
      dockerfile: joiner/ratings/ratings_joiner.dockerfile
    depends_on:
      monitor_1:
        condition: service_started
      monitor_2:
        condition: service_started
      monitor_3:
        condition: service_started
      monitor_4:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      worker:
        condition: service_started
    environment:
    - PYTHONUNBUFFERED=1
    - LOG_LEVEL=INFO
    - MONITOR_HOSTS=monitor_1,monitor_2,monitor_3,monitor_4
    - MONITOR_PORTS=50001,50002,50003,50004
    - HEARTBEAT_INTERVAL=5000
    - SERVICE_NAME=ratings_joiner
    - RATINGS_AGGREGATOR_HOST=best_and_worst_ratings_aggregator
    - RATINGS_AGGREGATOR_PORT=60001
    image: ratings_joiner:latest
    links:
    - rabbitmq
  sentiment_aggregator:
    build:
      context: .
      dockerfile: aggregator/sentiment_aggregator/aggregator.dockerfile
    depends_on:
      monitor_1:
        condition: service_started
      monitor_2:
        condition: service_started
      monitor_3:
        condition: service_started
      monitor_4:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      worker:
        condition: service_started
    environment:
    - PYTHONUNBUFFERED=1
    - LOG_LEVEL=INFO
    - MONITOR_HOSTS=monitor_1,monitor_2,monitor_3,monitor_4
    - MONITOR_PORTS=50001,50002,50003,50004
    - HEARTBEAT_INTERVAL=5000
    - SERVICE_NAME=sentiment_aggregator
    links:
    - rabbitmq
  sentiment_filter:
    build:
      context: .
      dockerfile: filters/sentiment_analizer/sentiment_analizer.dockerfile
    depends_on:
      monitor_1:
        condition: service_started
      monitor_2:
        condition: service_started
      monitor_3:
        condition: service_started
      monitor_4:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      worker:
        condition: service_started
    environment:
    - PYTHONUNBUFFERED=1
    - LOG_LEVEL=INFO
    - MONITOR_HOSTS=monitor_1,monitor_2,monitor_3,monitor_4
    - MONITOR_PORTS=50001,50002,50003,50004
    - HEARTBEAT_INTERVAL=5000
    - SERVICE_NAME=sentiment_filter
    image: sentiment_filter:latest
    links:
    - rabbitmq
  top_10_credits_aggregator:
    container_name: aggregator_top_10
    build:
      context: .
      dockerfile: aggregator/top_10_credits_aggregator/aggregator.dockerfile
    depends_on:
      monitor_1:
        condition: service_started
      monitor_2:
        condition: service_started
      monitor_3:
        condition: service_started
      monitor_4:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      worker:
        condition: service_started
    environment:
    - PYTHONUNBUFFERED=1
    - LOG_LEVEL=INFO
    - MONITOR_HOSTS=monitor_1,monitor_2,monitor_3,monitor_4
    - MONITOR_PORTS=50001,50002,50003,50004
    - HEARTBEAT_INTERVAL=5000
    - SERVICE_NAME=top_10_credits_aggregator
    links:
    - rabbitmq
    ports:
    - 60002:60000
  top_5_countries_aggregator:
    build:
      context: .
      dockerfile: aggregator/top_aggregator/aggregator.dockerfile
    depends_on:
      monitor_1:
        condition: service_started
      monitor_2:
        condition: service_started
      monitor_3:
        condition: service_started
      monitor_4:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      worker:
        condition: service_started
    environment:
    - PYTHONUNBUFFERED=1
    - LOG_LEVEL=INFO
    - MONITOR_HOSTS=monitor_1,monitor_2,monitor_3,monitor_4
    - MONITOR_PORTS=50001,50002,50003,50004
    - HEARTBEAT_INTERVAL=5000
    - SERVICE_NAME=top_5_countries_aggregator
    links:
    - rabbitmq
  twentieth_century_arg_aggregator:
    build:
      context: .
      dockerfile: aggregator/twentieth_century_arg_aggregator/aggregator.dockerfile
    depends_on:
      monitor_1:
        condition: service_started
      monitor_2:
        condition: service_started
      monitor_3:
        condition: service_started
      monitor_4:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      worker:
        condition: service_started
    environment:
    - PYTHONUNBUFFERED=1
    - LOG_LEVEL=INFO
    - MONITOR_HOSTS=monitor_1,monitor_2,monitor_3,monitor_4
    - MONITOR_PORTS=50001,50002,50003,50004
    - HEARTBEAT_INTERVAL=5000
    - SERVICE_NAME=twentieth_century_arg_aggregator
    links:
    - rabbitmq
  twentieth_century_arg_esp_aggregator:
    build:
      context: .
      dockerfile: aggregator/twentieth_century_arg_esp_aggregator/aggregator.dockerfile
    depends_on:
      monitor_1:
        condition: service_started
      monitor_2:
        condition: service_started
      monitor_3:
        condition: service_started
      monitor_4:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      worker:
        condition: service_started
    environment:
    - PYTHONUNBUFFERED=1
    - LOG_LEVEL=INFO
    - MONITOR_HOSTS=monitor_1,monitor_2,monitor_3,monitor_4
    - MONITOR_PORTS=50001,50002,50003,50004
    - HEARTBEAT_INTERVAL=5000
    - SERVICE_NAME=twentieth_century_arg_esp_aggregator
    links:
    - rabbitmq
  twentieth_century_filter:
    build:
      context: .
      dockerfile: filters/twentieth_century/twentieth_century_filter.dockerfile
    depends_on:
      monitor_1:
        condition: service_started
      monitor_2:
        condition: service_started
      monitor_3:
        condition: service_started
      monitor_4:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      worker:
        condition: service_started
    environment:
    - PYTHONUNBUFFERED=1
    - LOG_LEVEL=INFO
    - MONITOR_HOSTS=monitor_1,monitor_2,monitor_3,monitor_4
    - MONITOR_PORTS=50001,50002,50003,50004
    - HEARTBEAT_INTERVAL=5000
    - SERVICE_NAME=twentieth_century_filter
    image: twentieth_century_filter:latest
    links:
    - rabbitmq
  twentieth_century_filter_1:
    depends_on:
      monitor_1:
        condition: service_started
      monitor_2:
        condition: service_started
      monitor_3:
        condition: service_started
      monitor_4:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      worker:
        condition: service_started
    environment:
    - PYTHONUNBUFFERED=1
    - MONITOR_HOSTS=monitor_1,monitor_2,monitor_3,monitor_4
    - MONITOR_PORTS=50001,50002,50003,50004
    - HEARTBEAT_INTERVAL=5000
    - SERVICE_NAME=twentieth_century_filter_1
    image: twentieth_century_filter:latest
    links:
    - rabbitmq
  worker:
    build:
      context: .
      dockerfile: worker/worker.dockerfile
    depends_on:
      monitor_1:
        condition: service_started
      monitor_2:
        condition: service_started
      monitor_3:
        condition: service_started
      monitor_4:
        condition: service_started
    environment:
    - MONITOR_HOSTS=monitor_1,monitor_2,monitor_3,monitor_4
    - MONITOR_PORTS=50001,50002,50003,50004
    - HEARTBEAT_INTERVAL=5000
    - SERVICE_NAME=worker
    image: worker:latest
